module.exports = {
    "en": {
        "server_start": "Server started at ",
        "error_checking_trello_api": "Error checking Trello API: ",
        "checking_trello_api": "Checking Trello API...",
        "board_name": " | Board name: ",
        "hour": " | Hour: ",
        "new_changes": " | New changes: ",
        "new_action": "A new action has been found: ",
        "sending_to_discord": "Sending to Discord...",
        "error_sending_to_discord": "Error sending to Discord: ",
        "trello_create_card": "Create card:",
        "trello_create_card_desc": "A new card has been created.",
        "trello_desc": "Description",
        "trello_due_date": "Due date",
        "trello_dueComplete": "Completion status",
        "trello_idAttachmentCover": "Cover page",
        "trello_idChecklists": "Checklist",
        "trello_idMembers": "Members",
        "trello_idLabels": "Labels",
        "trello_idList": "List",
        "trello_update_card": "Update card:",
        "trello_update_card_desc": "A card has been updated.",
        "trello_previous_list": "Previous list",
        "trello_current_list": "Current list",
        "trello_previous_name": "Previous name",
        "trello_current_name": "Current name",
        "trello_previous_desc": "Previous description",
        "trello_current_desc": "Current description",
        "trello_previous_due": "Previous due date",
        "trello_current_due": "Current due date",
        "trello_previous_dueComplete": "Previous completion status",
        "trello_current_dueComplete": "Current completion status",
        "trello_previous_idAttachmentCover": "Previous cover",
        "trello_current_idAttachmentCover": "Current cover",
        "trello_previous_idChecklists": "Checklist added",
        "trello_delete_card": "Delete card",
        "trello_delete_card_desc": "A card has been deleted.",
        "trello_add_member_to_card": "Member added to card: ",
        "trello_add_member_to_card_desc": "A member has been added to a card.",
        "trello_remove_member_from_card": "Member removed from card: ",
        "trello_remove_member_from_card_desc": "A member has been removed from a card.",
        "trello_move_card_to_board": "Card moved to board: ",
        "trello_move_card_to_board_desc": "A card has been moved to another board.",
        "trello_update_list": "List updated:",
        "trello_update_list_desc": "The old name was:",
        "trello_archive_list": "List archived: ",
        "trello_archive_list_desc": "You helped a lot (probably?)",
        "trello_addChecklistToCard": "Checklist added to card: ",
        "trello_addChecklistToCard_desc": "A checklist has been added to a card.",
        "trello_removeChecklistFromCard": "Checklist removed from card: ",
        "trello_removeChecklistFromCard_desc": "A checklist has been removed from a card.",
        "trello_updateCheckItemStateOnCard": "Checklist updated: ",
        "trello_updateCheckItemStateOnCard_desc": "A checklist item state has been updated.",
        "trello_updateCheckItemStateOnCard_name": "Name",
        "trello_updateChecklist": "Update checklist: ",
        "trello_updateChecklist_desc": "A checklist has been updated.",
        "trello_updateChecklist_previous_name": "Previous name",
        "trello_updateChecklist_current_name": "Current name",
        "trello_commentCard_title": "Card commented:",
        "trello_commentCard_description": "Author:",
        "trello_commentCard_text": "Comment:",
        "trello_createList_title": "List created:",
        "trello_createList_description": "Author:",
        "trello_addMemberToBoard_title": "Member added:",
        "trello_addMemberToBoard_description": "Author:",
        "trello_copyCard_title": "Card copied",
        "trello_copyCard_description": "Author:",
        "trello_copyCard_original": "Original card:",
        "trello_copyCard_new": "New card:",
        "trello_addAttachmentToCard_title": "Attachment added to card:",
        "trello_addAttachmentToCard_description": "Filename:",
        "trello_action_not_supported": "Action not supported: ",
        "trello_action_not_supported_desc": "This action is not supported."
    },
};